Hyundai: Car Port for Nexo 2021
commaai/panda pull request #1637
Opened 2023-09-04 15:48 UTC by sunnyhaibin

**Prerequisite of**
- https://github.com/commaai/openpilot/pull/29771

2023-11-02 21:05 UTC, sshane commented
- [ ] Needs tests

2024-09-25 00:07 UTC, jyoung8607 requested changes
Looks reasonable at a glance, but as Shane mentioned, will need a test added. That's why CI isn't passing, because the FCEV code path isn't exercised at all.

2024-09-25 02:14 UTC, sunnyhaibin commented
> Looks reasonable at a glance, but as Shane mentioned, will need a test added. That's why CI isn't passing, because the FCEV code path isn't exercised at all.

Updated with unit test for FCEV.

2024-09-25 03:27 UTC, sunnyhaibin commented
> Looks reasonable at a glance, but as Shane mentioned, will need a test added. That's why CI isn't passing, because the FCEV code path isn't exercised at all.

Unite test updated and all passed.

2024-09-25 04:51 UTC, jyoung8607 approved these changes
LGTM

2024-09-25 05:07 UTC, sunnyhaibin commented
Awaiting for test route from user `simon402_61863 (Discord)`.

2024-09-25 05:11 UTC, jyoung8607 commented
The actual code here is GTM, but the original public test route has gone away, and we shouldn't merge this component without an immediate path to merging the opendbc port.

2025-02-23 04:15 UTC, sunnyhaibin commented
Safety is now migrated to `opendbc`!
- https://github.com/commaai/opendbc/pull/933

2025-02-23 04:15 UTC, closed without merging